### PR TITLE
Updated appforms backbone and feedhenry.js 

### PR DESCRIPTION
**Pull request by nialldonnellyfh**
These updates allow the display and validation of custom dateTime formats for the dateTime fields.

### CODE REVIEW

**Comment by nialldonnellyfh** [comment]
Related to https://github.com/feedhenry/fh-js-sdk/pull/173

**Comment by nialldonnellyfh** [comment]
Deployed to http://testing.ndonnelly.skunkhenry.com/#projects/j2a7pogpbioga7bnjkifwrm3/apps/j2a7pog4gzmjaqy7snv6uzpf/editor

@danbev If you get a chance, can you verify that the form is working correctly

**Comment by danbev** [comment]
👍  Looks good to me. Tried the validation and it works as advertised.

**Comment by nialldonnellyfh** [comment]
fhcap PR: https://github.com/fheng/fhcap/pull/1983

**Pull request merged**
