### PR TITLE
Updating minified fh-js-sdk to include RHMAP-4762

### PR DESCRIPTION
**Pull request by danbev**
Motivation:
Update fh-js-sdk to include the changes in RHMAP-4762

Modification:
Copied lib.min.js from Appforms-Template-v3/dist/www/lib.min.js

Result:
Updates for fh-js-sdk are availble i this template.

JIRA:
https://issues.jboss.org/browse/RHMAP-4762

### CODE REVIEW

**Comment by danbev** [comment]
@nialldonnellyfh Would you mind reviewing this one as well as I think I need to have this merged before I create the PR for fh-template-apps (even though I already submitted that PR, but I'll update it once this has been merged). And after that I'll create a PR for fhcap using the build from fh-template-apps.

**Comment by nialldonnellyfh** [comment]
@danbev Is this the app that was in your cluster?

**Comment by danbev** [comment]
Yes, this is same one. I imported it like you showed me yesterday.

tisdag 10 maj 2016 skrev nialldonnellyfh <notifications@github.com>:

**Comment by nialldonnellyfh** [comment]
@danbev Cool, feel free to merge and create the template apps PR

**Comment by danbev** [comment]
@nialldonnellyfh thanks!

**Pull request merged**
